{{- $fullname := include "omicx.name" . }}
{{- range $deployment := .Values.deployments }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullname }}-{{ $deployment.name }}-{{  $deployment.service.port }}-service"
spec:
  type: {{  $deployment.service.type }}
  ports:
    - port: {{  $deployment.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if $deployment.service.grpcPort}}
    - port: {{  $deployment.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    {{- end}}
  selector: 
    app: "{{ $fullname }}-{{ $deployment.name }}-deployment"
---
{{- end }}
