{{- $fullname := include "omicx.name" . }}
{{- if and $.Values.global $.Values.global.envs $.Values.global.envs.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullname }}-global-secret"
type: Opaque
data:
  {{- range $key, $val := $.Values.global.envs.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end -}}
{{- end -}}