{{- $fullname := include "omicx.name" . }}
{{- range $deployment := .Values.deployments }}
{{- if $deployment.envs.secret -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $fullname }}-{{ $deployment.name }}-secret"
type: Opaque
data:
  {{- range $key, $val := $deployment.envs.secret }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end -}}
---
{{- end -}}
{{- end }}