app:
  #  env: local
  port: 8080
  allowed_hosts: "*"

database:
  host: 103.141.141.60
  port: 15432
  user: postgres
  password: Default#Postgres@6699
  name: dev-contact-service
kafka:
  brokers:
    - omicx-kafka-0.omicx-kafka-headless.omicx-v2-dev.svc.cluster.local:9092
  security_protocol: SASL_PLAINTEXT
  sasl_mechanisms: CRAM-SHA-512
  sasl_username: kafka-admin
  sasl_password: Metech123
